### ISSUE TITLE
Not currently installing on Pixel 3

### ISSUE THREAD

**Issue by JansenSmith** [theflopguy/TickTrack#1]

**Comment by JansenSmith** [comment]
![Screenshot_20221126-145119](https://user-images.githubusercontent.com/6589862/204106722-f9dcc489-6935-46b0-9ba9-e964d734ed22.png)

**Comment by rahulnsanand** [comment]
Hi,

Thanks for bringing this issue to light. I observed the same with my Pixel and other 64bit architecture devices.

I have worked upon an update which is currently under testing. Will be releasing the same to prod in a day or two!

**Comment by rahulnsanand** [comment]
This issue seems to be fixed with the latest update.

**Comment by JansenSmith** [comment]
okay, i'll try it. thanks!
